name: DoSpark
description: "A modern To-Do list app with notes functionality."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  lottie: ^3.2.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4  # Updated from ^0.8.0 to ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation.json
    - assets/DoSpark_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/DoSpark_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground Ascending adaptive_icon_foreground: "assets/DoSpark_logo.png"